### ISSUE TITLE
CPU only?

### ISSUE THREAD

**Issue by Brakebein** [cherubicXN/hawp#32]
I would like to test your pretrained model on some custom images. I tried to follow the instructions in your [inference](https://github.com/cherubicXN/hawp/tree/inference) branch. However, my graphics card is too old (although CUDA Compute Compatiblity 3.0 should be supported until CUDA Toolkit 10.2, I couldn't get it to work).

I tried to run the command:

    python -m hawp.predict --disable-cuda -o out/ example.png

but get the following error:

    AssertionError: Torch not compiled with CUDA enabled

Although, the readme is stating the `--disable-cuda` flag, it seems to be nowhere considered in `predict.py` or any other files.

Is there any way to test your code and pretrained model without CUDA?

**Comment by cherubicXN** [comment]
Hi there, 

Thanks for using our inference branch. I just updated the code and now it supports the inference on CPU devices. 

Please pull the latest version and try it. I will open this issue until all your related problems are solved.

Best,

Nan

**Comment by Brakebein** [comment]
Thank you very much for your quick response and support! I have tested the updated branch and it worked now with CPU only.

**Comment by cherubicXN** [comment]
Thanks!
